name: BookDupe
main: in.nikitapek.bookdupe.BookDupePlugin
load: POSTWORLD
version: ${project.version}
author: Indiv0
description: A plugin to allow the easy duplication of books.
dev-url: http://github.com/Indiv0/BookDupe/

permissions:
  bookdupe.*:
    description: Controls all BookDupe copy permissions/restrictions
    children:
      bookdupe.any: true
      bookdupe.use: true
  bookdupe.any:
    description: Allows for the copying of any book from any author
    default: false
  bookdupe.use:
    description: Controls whether or not the user can use BookDupe
    default: false
